<?php

/**
 * Default system settings.
 *
 * Changes to these config files are not supported by BookStack and may break upon updates.
 * Configuration should be altered via the `.env` file or environment variables.
 * Do not edit this file unless you're happy to maintain any changes yourself.
 */

return [

    'app-name'             => env('APP_NAME', 'BookStack'),
    'app-logo'             => '',
    'app-name-header'      => true,
    'app-editor'           => 'wysiwyg',
    'app-color'            => '#1C2B39',
    'app-color-light'      => 'rgba(32,110,167,0.15)',
    'link-color'           => '#2d383c',
    'bookshelf-color'      => '#2d383c',
    'book-color'           => '#2d383c',
    'chapter-color'        => '#2d383c',
    'page-color'           => '#2d383c',
    'page-draft-color'     => '#2d383c',
    'app-color-dark'       => '#007AFF',
    'app-color-light-dark' => 'rgba(32,110,167,0.15)',
    'link-color-dark'      => '#D9D9D9',
    'bookshelf-color-dark' => '#D9D9D9',
    'book-color-dark'      => '#D9D9D9',
    'chapter-color-dark'   => '#D9D9D9',
    'page-color-dark'      => '#D9D9D9',
    'page-draft-color-dark' => '#D9D9D9',
    'app-custom-head'      => false,
    'registration-enabled' => true,
    'registration-confirmation' => true,
    'app-public' => true,

    // User-level default settings
    'user' => [
        'ui-shortcuts'          => '{}',
        'ui-shortcuts-enabled'  => false,
        'dark-mode-enabled'     => env('APP_DEFAULT_DARK_MODE', false),
        'bookshelves_view_type' => env('APP_VIEWS_BOOKSHELVES', 'grid'),
        'bookshelf_view_type'   => env('APP_VIEWS_BOOKSHELF', 'grid'),
        'books_view_type'       => env('APP_VIEWS_BOOKS', 'grid'),
    ],

];
